# logging
spring.main.banner-mode=console
logging.pattern.console=\
  { \
    %clr(\"time\": \"%d\"){blue}, \
    %clr(\"env\":\"${environment}\"){faint}, \
    %clr(\"version\": \"@project.name@/@project.version@\"){red}, \
    %clr(\"level\": \"%p\"), \
    %clr(\"PID\":\"${PID}\"){yellow}, \
    %clr(\"source\": \"%logger{63}:%L\"){magenta}, \
    \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\" \
  }%n