jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

springdoc.swagger-ui.path=/swagger-ui.html

# logging
spring.main.banner-mode=console
logging.pattern.console=\
  { \
    %clr(\"level\": \"%p\"), \
    %clr(\"source\": \"%logger{63}:%L\"){magenta}, \
    \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\" \
  }%n